app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/com/zipdabang/zipdabang_android/core/messaging/FirebaseCloudMessagingService.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/main/MainActivity.kt, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml
fcm 기능에 필요한 토큰을 파이어베이스 서버로부터 가져오고, 이를 로컬 저장소에 저장
성능저하가 발생할 가능성이 있는 코드는 추후 문제 발생 시 개선 예정
코드는 모두 정상적으로 동작해야 합니다.
=> :sparkles: [FEAT] Deriving FCM token from Firebase + storing token into datastore

app/src/main/java/com/zipdabang/zipdabang_android/ui/component/RadioGroup.kt
to prevent ripple effect
radio button ripple effect
x
코드는 모두 정상적으로 동작해야 합니다.
=> :lipstick: [FIX] radio button ripple effect removed

app/build.gradle.kts, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/RecipeNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/Screen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/common/RecipeListTitle.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeCard.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeCategoryTitle.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeList.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeListContent.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeListScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/data/common/RecipeListRepositoryImpl.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/domain/RecipeListRepository.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/domain/mediator/OwnerTypeRecipeListMediator.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/viewmodel/RecipeListViewModel.kt
ui logic implementation
레시피 카테고리(음료/작성자) 별 리스트 UI 로직을 구현
백엔드에 저장되어있는 데이터와 여기서 표출되는 데이터 비교 필요
모두 정상적으로 동작
=> :lipstick: [FEAT] Recipe List by Category UI Logic Implementation

app/src/main/java/com/zipdabang/zipdabang_android/common/ResponseCode.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/RecipeNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/SharedNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/RecipeDetailScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/data/Ingredient.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/data/RecipeDetailDto.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/data/RecipeDetailRepositoryImpl.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/data/RecipeDetailResult.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/data/RecipeInfo.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/data/RecipeStep.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/domain/RecipeDetailDomain.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/domain/RecipeDetailRepository.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/mapper/RecipeDetailMapper.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/ui/RecipeDetailState.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/ui/RecipeDetailViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/use_case/GetRecipeDetailUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/common/RecipeSubtitleState.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeList.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeListScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/data/RecipeApi.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/di/RecipeModule.kt, app/src/main/java/com/zipdabang/zipdabang_android/ui/component/AppBar.kt
레시피 상세화면에 대한 비즈니스 로직을 구현
없음. ui랑 연결할 때 테스트 필요
코드는 모두 정상적으로 동작
=> :sparkles: [FEAT] Recipe Detail Business Logic Implementation

app/src/main/java/com/zipdabang/zipdabang_android/module/market/ui/MarketScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/ui/component/Banner.kt
배너 개수 제한 삭제함
ex) [chore] QA 이슈 수정 #86
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브
=> :bug: [FIX] 배너 개수 제한 삭제

app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/DrawerNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/Screen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/drawer/ui/UserInfoBasicScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/drawer/ui/UserInfoDetailScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/drawer/ui/UserInfoNicknameScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/MyScreen.kt, app/src/main/res/values/strings.xml
앞으로 레시피 작성, 좋아요, 스크랩, 친구목록 UI 만들예정
=> :lipstick: [FEAT] Complete UserInfoEditScreen UI

app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/RecipeNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeListScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/data/RecipeApi.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipeScreen.kt
Recipe Category의 API 변경으로 관련 사항 반영
없음
정상적으로 동작
=> :alien: [REFACTOR] Recipe Category API Change 반영

app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/RecipeNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeCard.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeList.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeListContent.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeListScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipeMenuScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipePreviewByOwner.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipeScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/viewmodel/RecipeListViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/ToggleLikeListUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/ToggleLikeUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/ToggleScrapListUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/ToggleScrapUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/ui/component/GroupHeader.kt
레시피 미리보기에서 좋아요와 스크랩 토글 작업을 수행
비회원일 경우 동작하지 않음
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브
=> ♻️ [REFACTOR] toggle preferences ui logic

app/src/main/java/com/zipdabang/zipdabang_android/common/TabItem.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/RecipeNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/Screen.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/SharedNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/data/RecipeInfo.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/mapper/RecipeDetailMapper.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/ui/RecipeDetailPreference.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/ui/RecipeDetailScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/ui/RecipeDetailViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/ui/RecipeInfoPage.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/ui/RecipeIngredients.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/ui/RecipeIntro.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/ui/RecipeSteps.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/use_case/GetRecipeDetailUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/ui/component/AppBar.kt, app/src/main/java/com/zipdabang/zipdabang_android/ui/component/Pager.kt
레시피 상세 화면 성능 개선을 위한 Refactoring을 실시합니다.
없음
모두 정상적으로 동작
=> [REFACTOR] Recipe Detail Screen Navigation + UI Logic

app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/MyNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/drawer/ui/viewmodel/DrawerUserInfoViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/MyScreenForNotUser.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/RecipeWriteScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/ui/component/TextField.kt, app/src/main/res/values/strings.xml
Textfiled Component에서 하현이가 쓸건 TextFieldForContent()입니다! error날때 label을 이용해서 errorMessage를 띄우려 했는데 그렇게 하면 디자인이 좀 이상해져서(주석 해놨으니 직접 확인바람!) 하현이가 직접 수정하면서 쓰면 좋을 것 같습니다.
내집다방 비회원일때 UI를 디자인 해놨는데, MynavGraph에서 token에 accessToken이 ""이 아니면 회원일테니 MyScreen으로 넘어가게 하고 accessToken이 ""이면 MyScreenForNotUser로 넘어가게 로직을 짜려했습니다. accessToken을 스냅샷이 아닌  ProtoDataViewModel에서 accessToken만을 가져오고 싶은데 어떻게 해야할지 모르겠어서 일단 남겨봅니다..! (기문이형이 ProtoDataViewModle에서 함수 하나 더 만들어주는게 더 좋을지 아님 더 나은 방법이 있을지 모르겠어요)
이슈가 하나 있다면, 이제 MyScreenForNotUser에서 원래는 AUTH_ROUTE로 이동해야하는데 그렇게 하면 앱이 터져버리는게 문제입니다. MyScreen에서 onClickLogout 매개변수에서도 AUTH_ROUTE로 이동했어야 하는데 앱이 터져서 MAIN_ROUTE로 설정해뒀습니다. 도와주세요.. (별거 아닌것 같은데 모르겠어요)
=> :art: [ADD] MyScreenForNotUser and [FIX] Textfield component

app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/MyScreenForNotUser.kt
=> commit for merge to main

app/src/main/java/com/zipdabang/zipdabang_android/core/data_store/proto/ProtoDataViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/data_store/proto/ProtoRepositoryImpl.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/AuthNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/MainNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/MyNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/RootNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/main/MainScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/MyApi.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/SignOutResponseDto.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/SignOutResult.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/SignOutTokens.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/repository/MyRepositoryImpl.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/domain/SignOutResponse.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/domain/repository/MyRepository.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/MyScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/SignOutState.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/viewmodel/MyViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/use_case/SignOutUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/util/MyPageMapper.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/splash/use_case/CheckAccessTokenUseCase.kt
임시 유저의 로그인과 로그아웃 기능을 구현
코드 변경으로 영향이 가는 부분들이 있다면 체크해서 연락 요망
로그아웃 제외 정상적으로 동작
=> ✨ [FEAT] 임시 유저 로그인, 유저 로그아웃 Business Logic

app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/SharedNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/search/data/dto/recipecategory/SearchRecipeCategoryMediator.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/search/ui/SearchCategoryPreview.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/search/ui/SearchCategoryScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/search/ui/SearchCategoryViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/search/ui/SearchScreen.kt
검색 후 나오는 결과와 recipe 디테일 스크린 연결
=> [REFACTOR] Detail Screen 연결

app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/MyApi.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/friendlist/follow/FollowDto.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/friendlist/follow/FollowMediator.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/friendlist/following/FollowingDto.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/friendlist/following/FollowingMediator.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/repository/MyRepositoryImpl.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/domain/repository/MyRepository.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/domain/repository/PagingFollowRepository.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/domain/repository/PagingFollowingRepository.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/FollowScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/FollowingScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/component/FriendsItem.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/viewmodel/FriendsListViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/search/ui/SearchCategoryScreen.kt
=> 친구목록 비즈니스 로직 추가

app/src/main/java/com/zipdabang/zipdabang_android/common/ResponseBody.kt, app/src/main/java/com/zipdabang/zipdabang_android/common/TabItem.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/AppModule.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/HotRecipe.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeCategoryTitle.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeListContent.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/data/RecipeApi.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/data/common/RecipeListRepositoryImpl.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/data/hot/HotRecipeDto.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/data/hot/HotRecipeItem.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/domain/HotRecipe.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/domain/RecipeListRepository.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/mapper/RecipeMapper.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipeMenuScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipeScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/hot/HotCoffeeRecipeList.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/hot/HotRecipeItem.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/viewmodel/HotRecipeViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/viewmodel/RecipeMainViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/GetHotRecipesByCategoryUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/ui/component/Pager.kt, app/src/main/java/com/zipdabang/zipdabang_android/ui/theme/Type.kt
카테고리별 인기 레시피를 구현합니다.
pager 크기 주의하기
=> 💄:sparkles: [FEAT] 카테고리별 인기 레시피

app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/SharedNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/comment/ui/RecipeCommentViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/comment/ui/components/CommentItem.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/comment/ui/components/CommentSubmit.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/comment/use_case/BlockUserUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/comment/use_case/DeleteCommentUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/comment/use_case/EditCommentUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/comment/use_case/PostCommentUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/comment/use_case/ReportCommentUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/use_case/GetRecipeDetailUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/use_case/ReportRecipeUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/login/use_case/GetAuthResultUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/login/use_case/GetTempLoginResultUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/use_case/SignOutUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/GetRecipeBannerUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/GetRecipeCategoryUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/GetRecipePreviewUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/ToggleLikeListUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/ToggleLikeUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/ToggleScrapListUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/ToggleScrapUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/splash/use_case/CheckAccessTokenUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/splash/use_case/GetNewTokenUseCase.kt
http error 코드 핸들링 방식 변경으로 인한 use case 예외 처리 로직 변경
모든 기능이 이전과 동일하게 동작해야 함
=> :alien: [REFACTOR] http error 코드 핸들링 방식 변경으로 인한 use case 예외 처리 로직 변경

app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/MyScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/ui/theme/Type.kt
=> :lipstick: [FIX] Myscreen.kt

app/src/main/java/com/zipdabang/zipdabang_android/core/AppModule.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/comment/ui/RecipeCommentViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/common/RecipeSort.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeList.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeListContent.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeListScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/data/common/RecipeListRepositoryImpl.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/domain/RecipeListRepository.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/viewmodel/RecipeListViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/GetCategoryItemCountUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/GetOwnerItemCountUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/ui/component/Spinner.kt
디자인 추가로 레시피 리스트 화면 전체 개수 표출 및 정렬 기능 구현
추후 리스트 로그가 여러 번 찍히는 상황에 대한 성능 향상 필요
=> :sparkles: [FEAT] 레시피 리스트 전체 개수 표출 및 정렬

app/src/main/java/com/zipdabang/zipdabang_android/common/TabItem.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/MyNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/Screen.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/SharedNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/MyApi.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/otherinfo/MemberPreferCategoryDto.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/otherinfo/OtherInfoDto.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/otherinfo/OtherInfoResult.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/otherinfo/OtherPreferCategory.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/otherinfo/OtherRecipePreviewDto.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/otherinfo/OtherRecipePreviewResult.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/repository/MyRepositoryImpl.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/domain/repository/MyRepository.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/domain/usecase/GeOtherInfoUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/domain/usecase/GeOtherRecipePreviewUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/FollowScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/FollowingScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/FriendListScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/MyScreenForOther.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/ProfileForOthers.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/RecipeForOthers.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/component/FriendsItem.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/state/CommonInfoState.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/state/OtherInfo.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/state/OtherRecipeState.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/state/ProfileState.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/viewmodel/MyForOthersViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/ui/component/Pager.kt
=> :sparkles: [FEAT] 다른 사람 집다방 프로필

app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/RecipeWriteResponse.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/MyScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/RecipeWriteScreen.kt
내집다방에서 '프로필 편집하기' 누르면 레시피 작성가능해요. 근데 아직 카메라는 안됨..
=> [SUCCESS] RecipeWriteScreen.kt

app/src/main/java/com/zipdabang/zipdabang_android/common/TabItem.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/MyInfoScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/MyScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/sign_up/data/remote/AuthResponse.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/sign_up/data/remote/BeveragesResponse.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/sign_up/data/remote/InfoRequest.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/sign_up/data/remote/NicknameResponse.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/sign_up/data/remote/TermsResponse.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/sign_up/domain/usecase/GetBeveragesUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/sign_up/domain/usecase/GetTermsUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/sign_up/ui/viewmodel/AuthSharedViewModel.kt
최종 post api fcmtoken serialNumber 추가
=> :alien: [FIX] 최종 post api, add fcmToken and serialNumber

app/src/main/java/com/zipdabang/zipdabang_android/common/TabItem.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/DrawerNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/MyNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/MyPagerInfoScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/MyPagerProfileScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/MyPagerRecipesScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/MyScreen.kt
=> :lipstick: [COMPLETE] MyScreen UI

app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/MyNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/MyApi.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/recipewrite/RecipeWriteBeverageResult.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/recipewrite/RecipeWriteBeveragesResponse.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/repository/MyRepositoryImpl.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/domain/repository/MyRepository.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/domain/usecase/GetRecipeWriteBeveragesUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/RecipeWriteScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/state/recipewrite/RecipeWriteBeveragesEvent.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/state/recipewrite/RecipeWriteBeveragesState.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/state/recipewrite/RecipeWriteFormEvent.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/state/recipewrite/RecipeWriteFormState.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/viewmodel/RecipeWriteViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/ui/component/Button.kt, app/src/main/java/com/zipdabang/zipdabang_android/ui/component/DialogBackground.kt
=> :lipstick: [COMPLETE] RecipeWriteScreen without Camera and Saving api

app/src/main/java/com/zipdabang/zipdabang_android/common/ResponseCode.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/MyApi.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/recipewrite/CategoriesResult.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/recipewrite/RecipeWriteRequest.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/recipewrite/RecipeWriteTempContent.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/recipewrite/RecipeWriteTempIngredient.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/recipewrite/RecipeWriteTempResponse.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/recipewrite/RecipeWriteTempResult.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/recipewrite/RecipeWriteTempStep.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/repository/MyRepositoryImpl.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/domain/repository/MyRepository.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/domain/usecase/PostRecipeWriteTempUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/RecipeWriteScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/viewmodel/RecipeWriteViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/ui/component/DialogBackground.kt
=> :white_check_mark: [FIX] RecipeWriteScreen Category Dialog

app/src/main/java/com/zipdabang/zipdabang_android/core/messaging/FirebaseCloudMessagingService.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/HomeNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/MainNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/RecipeNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/RootNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/SharedNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/home/ui/HomeScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeList.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeListScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/login/di/LoginModule.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/login/ui/LoginScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/login/ui/LoginViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/login/use_case/GetAuthResultUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/main/FCMData.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/main/MainActivity.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/main/MainScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/main/NotificationViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/main/common/FCMData.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/main/common/NotificationTarget.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/main/data/DeletedTime.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/main/data/NotificationApi.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/main/data/NotificationRepositoryImpl.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/main/di/NotificationModule.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/main/domain/NotificationRepository.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/main/use_case/DeleteNotificationUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/splash/ui/SplashScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/splash/ui/SplashViewModel.kt
FCM 메시지 클릭 시 화면이동 구현
navgraph가 위치한 곳에 화면 이동(navigate) 로직을 구현하여야 뒤로가기 로직이 잘 동작
=> ✨ [FEAT] FCM 메시지 클릭 시 화면이동 구현

app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/RecipeNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeListScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipeScreen.kt
=> :sparkles: [FEAT] 앱바 검색 아이콘 클릭 시 검색으로 이동

app/src/main/java/com/zipdabang/zipdabang_android/module/comment/use_case/BlockUserUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/comment/use_case/DeleteCommentUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/comment/use_case/EditCommentUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/comment/use_case/PostCommentUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/comment/use_case/ReportCommentUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/use_case/CancelBlockUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/use_case/DeleteRecipeUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/use_case/GetRecipeDetailUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/use_case/ReportRecipeUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/login/use_case/GetAuthResultUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/login/use_case/GetTempLoginResultUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/use_case/SignOutUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/GetHotRecipesByCategoryUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/GetRecipeBannerUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/GetRecipeCategoryUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/GetRecipePreviewUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/ToggleLikeListUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/ToggleLikeUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/ToggleScrapListUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/ToggleScrapUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/splash/use_case/CheckAccessTokenUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/splash/use_case/GetNewTokenUseCase.kt
http errorbody string() 메소드 활용 관련 이슈
=> :bug: [FIX] http errorbody string() 메소드 활용 관련 이슈

app/src/main/java/com/zipdabang/zipdabang_android/core/Paging3Database.kt
=> :bug: [FIX] 룸디비 버전 설정

app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/ui/RecipeDetailScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/ui/component/AppBar.kt
디자인 변경 - 레시피 상세 화면 앱바 타이틀 추가 
스크롤 안 되었을 때는 투명, 스크롤 되었을 때에는 Typo 색깔
=> :lipstick: [FIX] 레시피 상세 화면 앱바 타이틀 추가

app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/MyPagerRecipesScreen.kt
=> :building_construction: [FIX] MyPagerRecipeScreen ShimmeringEffect

app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/domain/RecipeDetailDomain.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/ui/RecipeInfoPage.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/ui/RecipeTimeExpected.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/util/RecipeDetailMapper.kt
레시피 상세 화면 소요 시간 추가
모든 기능은 원래대로 동작되어야 함
=> :sparkles: [FEAT] 레시피 상세 페이지 소요 시간 추가

app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/SharedNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/detail/recipe/ui/RecipeDetailViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeListContent.kt
레시피 삭제 시 이전 화면이 아닌 홈 화면으로 이동하는 버그 수정
본래 기능들은 동일하게 동작
=> :bug: [FIX] 레시피 삭제 시 화면 이동 버그 수정

app/src/main/java/com/zipdabang/zipdabang_android/common/TabItem.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/ZipdabangApplication.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/RecipeNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeCategory.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeCategoryTitle.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeListScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/common/QueryType.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipeBanner.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipeCategory.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipeOwnerCategory.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipeScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/hot/HotRecipeItem.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/hot/HotRecipeList.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/viewmodel/RecipeMainViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/ui/component/Banner.kt, app/src/main/java/com/zipdabang/zipdabang_android/ui/component/BounceClick.kt, app/src/main/java/com/zipdabang/zipdabang_android/ui/component/CircleImage.kt
서버에서 보내는 이미지의 변경이 발생하면 새로운 이미지가 아닌 기존의 이미지가 표출되는 현상 해결
기존의 다른 기능은 모두 정상적으로 동작해야 한다.
=> :bug: [FIX] 레시피 메인 화면 Coil 캐싱 기능 비활성화

app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/DrawerNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/ui/component/Drawer.kt
더보기 회원아닐 경우, 내집다방 Home으로 넘어가게끔 처리해놓음
=> :white_check_mark: [ADD] Add DrawerScreen Page move for Not User

app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/DrawerNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/HomeNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/MyNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/RecipeNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/Screen.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/SharedNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/drawer/ui/NoticeScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/drawer/ui/quit/QuitScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/drawer/ui/report/ReportDetailScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/drawer/ui/report/ReportListScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/guide/ui/GuideScreen1.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/home/data/bestrecipe/BestRecipe.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/home/ui/HomeScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/MyScreenForOther.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/search/ui/SearchCategoryScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/search/ui/SearchScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/search/ui/SearchViewModel.kt
=> :sparkles: [FEAT] 베스트 레시피 차단 사용자 알럿

app/src/main/java/com/zipdabang/zipdabang_android/module/login/ui/LoginScreen.kt
로그인 로딩 중 인디케이터 추가
소셜 로그인은 정상적으로 동작해야 함
=> :lipstick: [FEAT] 로그인 로딩 중 인디케이터 추가

app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeListContent.kt
레시피 리스트 append 로딩 시 indicator 추가
다른 기능들은 원래대로 동작해야 함
=> :lipstick: [FEAT] 레시피 리스트 append 로딩 시 indicator 추가

app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/RecipeWriteScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/component/recipewrite/Step.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/viewmodel/RecipeWriteViewModel.kt
=> :lipstick: [ADD] Delete button for empty Step

app/src/main/java/com/zipdabang/zipdabang_android/module/bottom/ui/BottomNavigationBar.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/guide/ui/HomeBanner/HomeGuideBanner_1.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/MyApi.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/userreport/UserReportDto.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/remote/userreport/UserReportResult.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/data/repository/MyRepositoryImpl.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/domain/repository/MyRepository.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/domain/usecase/UserReportUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/FollowScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/FollowingScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/MyScreenForOther.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/component/DropDownForOther.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/component/FriendsItem.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/state/CommonInfoState.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/viewmodel/FriendsListViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/viewmodel/MyForOthersViewModel.kt
=> 유저 신고 기능 개발 및 바텀 폰트 수정

app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/DrawerNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/MyNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/RecipeNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/drawer/ui/PersonalInfoScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/drawer/ui/ServiceScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/drawer/ui/UserInfoProfileScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/drawer/ui/report/ErrorReportScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/drawer/ui/report/ReportListScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/FollowScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/FollowingScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/MyPagerInfoScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/RecipeWriteScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/state/myrecipe/write/RecipeWriteDialogEvent.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/state/myrecipe/write/RecipeWriteDialogState.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/viewmodel/RecipeWriteViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/ui/component/DialogBackground.kt, app/src/main/java/com/zipdabang/zipdabang_android/ui/component/Drawer.kt
더보기 뒤로가기 수정, 더보기 프로필 변경 및 레시피 관련 수정 및 추가
=> [FIX] UI and Logics

app/src/main/java/com/zipdabang/zipdabang_android/ui/component/AppBar.kt
레시피 상세 화면 appbar 스크롤 오류 해결
기존 기능의 원활한 동작 확인
=> :bug:💄 [FIX] 레시피 상세 화면 appbar 스크롤 오류 해결

app/build.gradle.kts, app/proguard-rules.pro, app/release/output-metadata.json, app/src/main/AndroidManifest.xml, app/src/main/java/com/zipdabang/zipdabang_android/core/AppModule.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/drawer/di/DrawerModule.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/home/di/HomeModule.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeCategoryTitle.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/item/recipe/ui/RecipeListScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/login/di/LoginModule.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/market/di/MarketModule.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/di/MyModule.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/use_case/ToggleScrapUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/search/di/SearchModule.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/sign_up/di/SignUpModule.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/sign_up/domain/usecase/GetTermsUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/splash/use_case/CheckAccessTokenUseCase.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/splash/use_case/GetNewTokenUseCase.kt
=> 👽 [MODIFY] 개발용/릴리즈용 BASE URL 변경

app/src/main/java/com/zipdabang/zipdabang_android/module/sign_up/ui/viewmodel/AuthSharedViewModel.kt
최종 회원정보 전송 시 플랫폼 전송 버그 해결
기존의 모든 동작들이 정상적으로 동작해야함
=> :bug: [FIX] 최종 회원정보 전송 시 플랫폼 전송 버그 해결

app/build.gradle.kts, app/src/main/java/com/zipdabang/zipdabang_android/common/LifeCycleEvent.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/RecipeNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/RecipeScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/viewmodel/HotRecipeViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/viewmodel/RecipeListViewModel.kt
레시피 리스트 화면 복귀 시 좋아요 및 스크랩 미반영 버그 해결
성능 상 이슈를 해결하는 것이 필요
=> :bug: [FIX] 레시피 리스트 화면 복귀 시 좋아요 및 스크랩 미반영 버그 해결

app/src/main/java/com/zipdabang/zipdabang_android/common/LifecycleEvent.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/RecipeNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/recipes/ui/viewmodel/RecipeListViewModel.kt
레시피 상세화면에서 좋아요/스크랩 클릭 후 리스트 복귀 시 반영되지 않는 버그 해결
이전의 동작들은 모두 정상동작해야함
=> :bug: [FIX] 레시피 상세화면에서 좋아요/스크랩 클릭 후 리스트 복귀 시 반영되지 않는 버그 해결

app/.gitignore, app/src/main/java/com/zipdabang/zipdabang_android/module/drawer/ui/report/ErrorReportScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/home/domain/usecase/GetBestRecipe.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/search/data/dto/common/SearchCategory.kt
=> [FIX] 화면 회전 오류 해결

app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/RecipeWriteScreen.kt
=> :bug: [FIX] Annotate RotateBitmap Function

app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/MyCompleteRecipesScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/RecipeWriteScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/viewmodel/MyRecipesViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/my/ui/viewmodel/RecipeWriteViewModel.kt
by jessy
ex) [chore] QA 이슈 수정 #86
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브
=> :bug: [FIX] Move to MyTempRecipesScreen After Uploading TempRecipes

app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/HomeNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/MainNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/core/navigation/SharedNavGraph.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/home/ui/HomeScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/home/ui/HomeViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/search/ui/SearchCategoryPreview.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/search/ui/SearchCategoryScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/search/ui/SearchCategoryViewModel.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/search/ui/SearchScreen.kt, app/src/main/java/com/zipdabang/zipdabang_android/module/search/ui/SearchViewModel.kt
계정이 없거나, 본인의 레시피가 아닐 때 좋아요, 스크랩 기능 방지
=> :zap: [FEAT] 좋아요, 스크랩 못 누를 때의 케이스 추가

app/src/main/java/com/zipdabang/zipdabang_android/module/search/ui/SearchCategoryPreview.kt
=> 스크랩 방지 기능 추가

README.md
README.md 버전 및 역할 업데이트
v2.0.5 버전 release 관련 사항 추가
=> :memo: [DOCS] README.md 버전 및 역할 업데이트
